### ISSUE TITLE
Admin : Gestion des informations affichées

### ISSUE THREAD

**Issue by ywsq** [Karitchi/infolab#38]
### Description

Une gestion centralisée de l'admin des informations qui seront affichées sur l'écran de l'openlab.

### User Role

en tant que administrateur

### Desired Outcome

je veux pouvoir ajouter, modifier ou supprimer des informations affichées (météo, horaires de train, annonces) afin de garantir que les utilisateurs aient accès à des informations à jour et pertinentes.

### Goal or Purpose

Le but est de pouvoir éviter que les informations affichées ne soient pas pertinentes et aussi régler leur ordre d'affichage ainsi que masquer certaines informations.

### Acceptance Criteria

- gérer l'ordre d'affichage des informations
- L'administrateur peut ajouter, modifier ou supprimer des informations affichées via une interface intuitive.
- Les modifications sont visibles sur l'écran en temps réel après validation.
- Un message de confirmation apparaît après chaque action (ajout, modification, suppression).

**Comment by Karitchi** [comment]
@ywsq je crois qu'il faudrait montrer/cacher des sections, pas vraiment les ajouter/supprimer et tu peux mettre la modification de l'ordre dans une 2ème feature à part
