### ISSUE TITLE
Dynamic Announcement Display for Dashboard

### ISSUE THREAD

**Issue by ywsq** [Karitchi/infolab#43]
### Description

The dashboard will feature an announcement panel specifically designed to display announcements, ensuring visibility to all students. Each announcement will include the following elements: a **title**, **description**, and **author**. If an **end date** is specified, the announcement will be automatically removed from the dashboard once that date is reached.

The announcements will automatically cycle through all available announcements horizontally, with each announcement displayed for a specified duration (e.g., **10 seconds**). After all announcements have been shown, the dashboard will smoothly transition vertically to present the next panel, ensuring a seamless flow of information throughout the user experience.

### User Role

As a user

### Desired Outcome

I want to view announcements on the dashboard

### Goal or Purpose

To communicate essential information to students in a visible and centralized manner without relying on verbal announcements, mail or paper notes.

### Acceptance Criteria

And I will be satisfied when:

1. Announcements are displayed on a designated panel within the dashboard's slideshow, with smooth horizontal transitions between different announcements(slides).
2. Each announcement includes a title, description, and author.
3. Announcements are removed from the dashboard automatically after the specified end date, if applicable.
4. The announcements are visible across all platforms (TV, PC, mobile).
5. Changes to announcements are reflected in real-time without the need to refresh the dashboard.
6. The feature is accessible and functional on all supported device types.

**Comment by Karitchi** [comment]
> Afficher sur l'ecran de l'openlab les informations de meteo, train, bus, annonces.

C'est juste afficher les annonces normalement
